/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
import java.awt.Color;
import java.sql.*;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Book_tickets extends javax.swing.JFrame {

    /**
     * Creates new form Book_tickets
     */
    public Book_tickets() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TF1 = new javax.swing.JTextField();
        TF2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        dc = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        T1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        busid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        adult = new javax.swing.JTextField();
        infant = new javax.swing.JTextField();
        sc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        ocode = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("AR JULIAN", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Book Tickets");

        jLabel2.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 204));
        jLabel2.setText("Customer Name");

        jLabel4.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 204));
        jLabel4.setText("TO");

        TF1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TF1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TF1FocusGained(evt);
            }
        });
        TF1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TF1KeyReleased(evt);
            }
        });

        TF2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TF2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TF2FocusGained(evt);
            }
        });
        TF2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TF2KeyReleased(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Aparajita", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 204));
        jLabel5.setText("DATE");

        dc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dcFocusGained(evt);
            }
        });
        dc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dcKeyPressed(evt);
            }
        });

        T1.setBackground(new java.awt.Color(255, 255, 102));
        T1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        T1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BUS ID", "BUS TYPE", "AVAILABLE SEATS", "DEPARTURE TIME", "ARRIVAL TIME", "BASE FARE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(T1);

        jLabel6.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 204));
        jLabel6.setText("FROM");

        name.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }
        });
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 204));
        jLabel7.setText("Bus ID");

        busid.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        busid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                busidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                busidFocusLost(evt);
            }
        });
        busid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                busidKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 204));
        jLabel8.setText("Passengers");

        adult.setText("0");
        adult.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                adultFocusGained(evt);
            }
        });

        infant.setText("0");
        infant.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                infantFocusGained(evt);
            }
        });

        sc.setText("0");
        sc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                scFocusGained(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 204));
        jLabel9.setText("Adult");

        jLabel10.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 204));
        jLabel10.setText("Infant");

        jLabel11.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 204));
        jLabel11.setText("Senior Citizen");

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setFont(new java.awt.Font("Aparajita", 1, 48)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 153));
        jButton2.setText("Book");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 204));
        jLabel12.setText("Order code");

        ocode.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ocode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ocodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ocodeFocusLost(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 255, 153));
        jButton3.setFont(new java.awt.Font("Utsaah", 1, 36)); // NOI18N
        jButton3.setText("Back to Homepage");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 255, 153));
        jButton4.setFont(new java.awt.Font("Utsaah", 1, 36)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(31, 31, 31)))
                            .addComponent(jLabel8))))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(27, 27, 27)
                                .addComponent(adult, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(busid, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(infant, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sc, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ocode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(name, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(dc, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(146, 146, 146)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3))
                                .addGap(191, 191, 191)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(TF2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(297, 297, 297)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(524, 524, 524)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(TF2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(dc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TF1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(ocode)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(name))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(busid, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(adult, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sc, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(infant, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 372, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        DefaultTableModel model=(DefaultTableModel) T1.getModel();
        int rows=model.getRowCount();
                     if (rows>0)
                     {
                         for(int i=0;i<rows;i++)
                             model.removeRow(0);
                     }
        
        try{
                Class.forName("java.sql.DriverManager");
                Connection con=DriverManager.getConnection("jdbc:mysql://Localhost:3306/project","root","root");
String s=TF1.getText(); String d=TF2.getText();String stt,sqlq,oid;int set;
 //date
                java.util.Date utilStartDate=dc.getDate();
java.sql.Date sqlStartDate=new java.sql.Date(utilStartDate.getTime());
        //date converted
                sqlq="select ifnull(max(ordercode),0) from booking;";
                
                String bdate=sqlStartDate.toString();


                String sql="select bus_id,bus_type,seats,departure_time,arrival_time,base_fare from bus_info where source='"+s+"' and destination='"+d+"';";
                
                Statement st=con.createStatement();
                 ResultSet rss=st.executeQuery(sqlq);
                if(rss.next())
                {oid=rss.getString("ifnull(max(ordercode),0)");
                  int orid=Integer.parseInt(oid);
               
                  ocode.setText(""+(orid+1));
                   }
                
                
                
                ResultSet rs=st.executeQuery(sql);
                
                {
                    boolean r=false;
                    while(rs.next())
                  {
                      r=true;
                      
                      String sql1="select busid,date,sum(tot_seat) from booking where busid='"+rs.getString("bus_id")+"'and date='"+bdate+"' group by busid,date;";
                      Statement st1=con.createStatement();
                      ResultSet rs1=st1.executeQuery(sql1);
                      set=Integer.parseInt(rs.getString("seats"));
                      if(rs1.next())
                      {
                          stt=rs1.getString("sum(tot_seat)");
                          set=set-Integer.parseInt(stt);
                          stt=Integer.toString(set);
                      }else
                      {
                          stt=rs.getString("seats");
                      }
                      DefaultTableModel T=(DefaultTableModel)T1.getModel();
                    Object newRow[]={rs.getString("bus_id"),rs.getString("bus_type"),stt,rs.getString("departure_time"),rs.getString("arrival_time"),rs.getString("base_fare")};
                T.addRow(newRow);
                  }

                 if(!r)
                 {
                    JOptionPane.showMessageDialog(null,"No buses");
                    TF1.setText("");
                    TF2.setText("");
                 }
               
             


                 }}

                 catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }




        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TF1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TF1FocusGained
 DefaultTableModel model=(DefaultTableModel) T1.getModel();
        int rows=model.getRowCount();
                     if (rows>0)
                     {
                         for(int i=0;i<rows;i++)
                             model.removeRow(0);
                     }
                     TF1.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_TF1FocusGained

    private void TF2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TF2FocusGained
 DefaultTableModel model=(DefaultTableModel) T1.getModel();
        int rows=model.getRowCount();
                     if (rows>0)
                     {
                         for(int i=0;i<rows;i++)
                             model.removeRow(0);
                     }
                     TF2.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_TF2FocusGained

    private void nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFocusGained

    private void busidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_busidFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_busidFocusGained

    private void adultFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adultFocusGained
adult.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_adultFocusGained

    private void infantFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_infantFocusGained
infant.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_infantFocusGained

    private void scFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_scFocusGained
sc.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_scFocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

       
        
        
        
        DefaultTableModel model=(DefaultTableModel) T1.getModel();
        
        try{
            Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection("jdbc:mysql://Localhost:3306/project","root","root");
            String bid,sql,bp,nm,sql1;
            int oc=Integer.parseInt(ocode.getText());
             //date
                java.util.Date utilStartDate=dc.getDate();
java.sql.Date sqlStartDate=new java.sql.Date(utilStartDate.getTime());
        //date converted
                
                
                String bdate=sqlStartDate.toString();
            
          
            
            nm=name.getText();
            bid=busid.getText();
             int ad=Integer.parseInt(adult.getText());
            int sen=Integer.parseInt(sc.getText());
            int inf=Integer.parseInt(infant.getText());
            
            
             
 int row=T1.getRowCount(),ss=0;
 int rindex=row;
 int index=0;
 while(index<rindex)
 {
  Object a=T1.getValueAt(index,0);
 
 String k=(String)a;
 if(k.equalsIgnoreCase(bid))
 {
     Object b=T1.getValueAt(index,2);
     ss=Integer.parseInt((String)b);
     break;
 }

 index++;
 }
            
            
         if(ss>(ad+sen))   
            
         {
            
            
            sql="select base_fare from bus_info where bus_id='"+bid+"'";
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(sql);
            if(rs.next())
            {bp=rs.getString("base_fare");
            
            float price=Float.parseFloat(bp);
           
                 double tot=(price*ad)+(price*sen*0.7);
             sql1="insert into booking values("+oc+",'"+bdate+"','"+nm+"','"+bid+"',"+(ad+sen)+","+ad+","+inf+","+sen+","+tot+")";
              
                st.execute(sql1);
           
       
            JOptionPane.showMessageDialog(null,"Thanks for riding with us "+nm+"\nYour total fare is rs"+tot);
            adult.setText(""+0);
 ocode.setText("");
 infant.setText(""+0);
 sc.setText(""+0);
 name.setText("");
 busid.setText("");
 TF1.setText("");
 TF2.setText("");
        int rows=model.getRowCount();
                     if (rows>0)
                     {
                         for(int i=0;i<rows;i++)
                             model.removeRow(0);
                     }
                     dc.setCalendar(null);
            }
            
                    
            
         }else
         {
             JOptionPane.showMessageDialog(null,"Please enter appropriate number of passengers");
             adult.setText(""+0);
 infant.setText(""+0);
 sc.setText(""+0);
             
         }
 }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void busidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_busidFocusLost
DefaultTableModel model=(DefaultTableModel) T1.getModel();
String s=busid.getText();
 int row=T1.getRowCount();
int i=0;
 int rindex=row;
 int index=0;
 
 while(index<rindex)
 {
  Object a=T1.getValueAt(index,0);
 
 String k=(String)a;
 if(k.equalsIgnoreCase(s))
 {
     i=1;
     break;
 }
 


 index++;




 }
 
 if(i==0)
 {
     JOptionPane.showMessageDialog(null,"Enter appropriate busid");
     busid.setText("");
 }
        // TODO add your handling code here:
    }//GEN-LAST:event_busidFocusLost

    private void ocodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ocodeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_ocodeFocusGained

    private void ocodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ocodeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_ocodeFocusLost

    private void dcFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dcFocusGained

                    
        // TODO add your handling code here:
    }//GEN-LAST:event_dcFocusGained

    private void dcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dcKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_dcKeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
new homepage().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TF1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TF1KeyReleased
String x=TF1.getText();
TF1.setText(x.toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_TF1KeyReleased

    private void TF2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TF2KeyReleased
String x=TF2.getText();
TF2.setText(x.toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_TF2KeyReleased

    private void nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyReleased
String x=name.getText();
name.setText(x.toUpperCase());

        // TODO add your handling code here:
    }//GEN-LAST:event_nameKeyReleased

    private void busidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busidKeyReleased
String x=busid.getText();
busid.setText(x.toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_busidKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Book_tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Book_tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Book_tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Book_tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Book_tickets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable T1;
    private javax.swing.JTextField TF1;
    private javax.swing.JTextField TF2;
    private javax.swing.JTextField adult;
    private javax.swing.JTextField busid;
    private com.toedter.calendar.JDateChooser dc;
    private javax.swing.JTextField infant;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField ocode;
    private javax.swing.JTextField sc;
    // End of variables declaration//GEN-END:variables
}
